development:
  adapter: postgresql
  host: localhost
  database: hazelnut_dev
  username: junona
  pool: 10
  timeout: 5000

heroku config:
#  set BUNDLE_WITHOUT="development:test"
  adapter: postgresql
  database: d91a8kk1ujl3iv
  host: ec2-54-204-35-132.compute-1.amazonaws.com
  user: ouyxobmmksjmai
  password: cXHtRgzFCPV6cTz57KUUBZReZY
  port: 5432
  sslmode: require

production:
  adapter: postgresql
  host: localhost
  database: hazelnut_prod
  username: junona
  pool: 10
  timeout: 5000
